# -*- coding: utf-8 -*-
"""Thang Nguyen_Unit Economics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kmK0M-_eybcpYMIJ5I0DPxm3cphAz1d3
"""

import pandas as pd

receipts_url = 'https://docs.google.com/spreadsheets/d/' + '1qayqML1zCKdmtzutkcy9LWvE6xFRm6TGBEVkHHJKIuE' + '/export?format=xlsx'
payroll_url = 'https://docs.google.com/spreadsheets/d/' + '1c_WihqTZCQvNgxzmd-OwhR9i5diwtfxXVLyMn8R-Lp4' + '/export?format=xlsx'
expenses_url = 'https://docs.google.com/spreadsheets/d/' + '10OGbaywwMIqKgnPGy8VDvpBVtjyqln47iYa2lFhI9Mw' + '/export?format=xlsx'
marketing_url = 'https://docs.google.com/spreadsheets/d/' + '1AZOIThOV4P-0eYDge53ZwumVkfkHoYPWxst3k3Bv87c' + '/export?format=xlsx'
customer_url = 'https://docs.google.com/spreadsheets/d/' + '1by8tPHwOnq3uKYK2E7sA9VBUYoPM4p1Rnrm_Ss9cyHI' + '/export?format=xlsx'
receipts_history = pd.read_excel(receipts_url, sheet_name='Sheet1')
payroll = pd.read_excel(payroll_url, sheet_name='Sheet1')
monthly_expenses = pd.read_excel(expenses_url, sheet_name='Sheet1')
daily_marketing_spendings = pd.read_excel(marketing_url, sheet_name='Sheet1')
customer_lifespan = pd.read_excel(customer_url, sheet_name='Sheet1')

con1 = monthly_expenses['month'].dt.month == monthly_expenses['month'].dt.month.max()
con2 = monthly_expenses['item'] == 'Salesforce'
last_expenses = monthly_expenses[con1 & con2]
last_total_expenses = last_expenses['amount'].sum()

con1 = payroll['month'].dt.month == payroll['month'].dt.month.max()
con2 = payroll['department'].isin(['Sales', 'Marketing'])
last_payroll = payroll[con1 & con2]
last_total_payroll = last_payroll['paid'].sum()

last_marketing = daily_marketing_spendings[daily_marketing_spendings['date'].dt.month == daily_marketing_spendings['date'].dt.month.max()]
last_total_marketing = last_marketing['spending'].sum()

con1 = receipts_history['date'].dt.month == receipts_history['date'].dt.month.max()
con2 = receipts_history['new_customer'] == 1
last_new_customer = receipts_history[con1 & con2]
last_new_customer_count = last_new_customer['customer_id'].count()

CAC = (last_total_expenses + last_total_payroll + last_total_marketing) / last_new_customer_count
CAC

con1 = monthly_expenses['month'].dt.month == monthly_expenses['month'].dt.month.max()
con2 = monthly_expenses['category'].isin(['Server Costs', 'Software Licenses'])
con3 = monthly_expenses['item'] != 'Salesforce'
last_server_license = monthly_expenses[con1 & con2 & con3]
last_total_server_license = last_server_license['amount'].sum()

con1 = payroll['month'].dt.month == payroll['month'].dt.month.max()
con2 = payroll['department'] == 'Engineering'
last_engineer_payroll = payroll[con1 & con2]
last_total_engineer_payroll = last_engineer_payroll['paid'].sum()

COGS = last_total_server_license + last_total_engineer_payroll
COGS

customer_lifespan['lifespan'] = (customer_lifespan['churn_date']- customer_lifespan['start_date']).dt.days
avg_lifespan = customer_lifespan['lifespan'].mean()
avg_lifespan